const data = [
  {
    id: 1,
    img: "./image/MI-140d Plus1.jpg",
    title: "140D Plus",
    star:"Large Calculator",
    prevPrice: "₹1199",
    newPrice: "600",
    price: "₹599",
    category:"l-display",
    color: "tgtkey",
    link:`/card140`,
  },
  {
    id: 2,
    img: "./image/912ND1.jpg",
    title: "912ND",
    star:"Large Calculator",
    prevPrice: "₹1149",
    newPrice: "600",
    price: "₹575",
    category: "l-display",
    color: "tgtkey",
    link:`/card912nd`,
  },
  {
    id: 3,
    img: "./image/MI-140GC1.jpg",
    title: "140GC",
    star:"Large Calculator",
    prevPrice: "₹1299",
    newPrice: "601",
    price: "₹649",
    category: "l-display",
    color: "tgtkey",
    link:`/card140gc`,
  },
  {
    id: 4,
    img: "./image/912GC1.jpg",
    title: "912GC",
    star:"Large Calculator",
    prevPrice: "₹1249",
    newPrice: "601",
    price: "₹625",
    category: "l-display",
    color: "tgtkey",
    link:`/card912gc`,
  },
  {
    id: 19,
    img: "./image/82MS1.jpg",
    title: "fx-82MS",
    star:"Scientific Calculator",
    prevPrice: "₹1174",
    newPrice: "600",
    price: "₹587",
    category: "scientific",
    color: "",
    link:`/card82ms`,    
  },
  {
    id: 5,
    img: "./image/121DLX1.jpg",
    title: "121 DLX",
    star:"Desk Calculator",
    prevPrice: "₹799",
    newPrice: "400",
    price: "₹399",
    category: "m-display",
    color: "tgtkey",
    link:`/card121dlx`,
  },
  {
    id: 6,
    img: "./image/141E1.jpg",
    title: "MI-141E",
    star:"Desk Calculator, Tilt Display",
    prevPrice: "₹1159",
    newPrice: "600",
    price: "₹579",
    category: "l-display",
    color: "tgtkey",
    link:`/card141e`,
  },  
  {
    id: 7,
    img: "./image/512GC1 WHITE.jpg",
    title: "MI-512GC",
    star:"Desktop Calculator",
    prevPrice: "₹819",
    newPrice: "600",
    price: "₹410",
    category: "m-display",
    color: "gtkey",
    link:`/card512gc`,
  },
  {
    id: 8,
    img: "./image/556N1.jpg",
    title: "MI-556N",
    star:"Desktop Calculator",
    prevPrice: "₹839",
    newPrice: "600",
    price: "₹419",
    category: "m-display",
    color: "tax",
    link:`/card556n`,
  },
  {
    id: 9,
    img: "./image/GT1.jpg",
    title: "MI-512GT",
    star:"Desktop Calculator",
    prevPrice: "₹779",
    newPrice: "400",
    price: "₹389",
    category: "m-display",
    color: "tax",
    link:`/card512gt`,
  },
  {
    id: 10,
    img: "./image/837N1.jpg",
    title: "MI-837N",
    star:"Desktop Calculator",
    prevPrice: "₹769",
    newPrice: "400",
    price: "₹385",
    category: "m-display",
    color: "gtkey",
    link:`/card837n`,
  },
  {
    id: 11,
    img: "./image/888N1.jpg",
    title: "MI-888N",
    star:"Desktop Calculator",
    prevPrice: "₹919",
    newPrice: "600",
    price: "₹459",
    category: "m-display",
    color: "gtkey",
    link:`/card888n`,
  },
  {
    id: 12,
    img: "./image/913VS2 copy.jpg",
    title: "913 VS",
    star:"Compact Calculator",
    prevPrice: "₹529",
    newPrice: "400",
    price: "₹265",
    category: "m-display",
    color: "black",
    link:`/card913vs`,
  },
  {
    id: 13,
    img: "./image/847-1.jpg",
    title: "MI-847",
    star:"Desktop Calculator",
    prevPrice: "₹799",
    newPrice: "400",
    price: "₹399",
    category: "m-display",
    color: "gtkey",
    link:`/card847`,
  },
  {
    id: 14,
    img: "./image/786N1.png.jpg",
    title: "MI-786N",
    star:"Desktop Calculator",
    prevPrice: "₹Free",
    newPrice: "400",
    price: "₹Free",
    category: "m-display",
    color: "gtkey",
    link:`/card786n`,
  },
  {
    id: 15,
    img: "./image/120d1.jpg",
    title: "MJ-120D",
    star:"Desktop Calculator",
    prevPrice: "₹859",
    newPrice: "600",
    price: "₹429",
    category: "m-display",
    color: "tgtkey",
    link:`/card120d`,
  },
  {
    id: 16,
    img: "./image/513WT1.jpg",
    title: "WT-513",
    star:"Desktop Calculator",
    prevPrice: "₹549",
    newPrice: "400",
    price: "₹275",
    category: "m-display",
    color: "gtkey",
    link:`/card513`,
  },
  {
    id: 17,
    img: "./image/912VS1.jpg",
    title: "MI-912",
    star:"Compact Calculator",
    prevPrice: "₹459",
    newPrice: "400",
    price: "₹229",
    category: "m-display",
    color: "black",
    link:`/card912`,
  },
  // {
  //   id: 18,
  //   img: "./image/222N1.jpg",
  //   title: "MI-222N",
  //   star:"Gold Large Calculator",
  //   prevPrice: "₹399",
  //   newPrice: "200",
  //   price: "₹199",
  //   category: "m-display",
  //   color: "black",
  // link:`/probir`,
  // },
 
  // {
  //   id: 20,
  //   img: "./image/200N1.jpg",
  //   title: "MI-200N",
  //   star:"Gold Large Calculator",
  //   prevPrice: "₹219",
  //   newPrice: "200",
  //   price: "₹109",
  //   category: "s-display",
  //   color: "black",
  // },
  {
    id: 21,
    img: "./image/201N1.jpg",
    title: "MI-201N",
    star:"Pocket Calculator",
    prevPrice: "₹249",
    newPrice: "200",
    price: "₹125",
    category: "s-display",
    color: "black",
    link:`/card201`,
  },
];

export default data;
