const data = [
  {
    id: 1,
    img: "./image/MI-140d Plus1.jpg",
    title: "140D Plus",
    star:"Large Calculator",
    prevPrice: "₹600",
    newPrice: "501",
    price: "₹420",
    category:"l-display",
    color: "tgtkey",
    link:`/card140`,
  },
  {
    id: 2,
    img: "./image/912ND1.jpg",
    title: "912ND",
    star:"Large Calculator",
    prevPrice: "₹575",
    newPrice: "501",
    price: "₹402",
    category: "l-display",
    color: "tgtkey",
    link:`/card912nd`,
  },
  {
    id: 3,
    img: "./image/MI-140GC1.jpg",
    title: "140GC",
    star:"Large Calculator",
    prevPrice: "₹650",
    newPrice: "501",
    price: "₹455",
    category: "l-display",
    color: "tgtkey",
    link:`/card140gc`,
  },
  {
    id: 4,
    img: "./image/912GC1.jpg",
    title: "912GC",
    star:"Large Calculator",
    prevPrice: "₹625",
    newPrice: "501",
    price: "₹438",
    category: "l-display",
    color: "tgtkey",
    link:`/card912gc`,
  },
  {
    id: 19,
    img: "./image/82MS1.jpg",
    title: "fx-82MS",
    star:"Scientific Calculator",
    prevPrice: "₹587",
    newPrice: "501",
    price: "₹410",
    category: "scientific",
    color: "",
    link:`/card82ms`,    
  },
  {
    id: 5,
    img: "./image/121DLX1.jpg",
    title: "121 DLX",
    star:"Desk Calculator",
    prevPrice: "₹400",
    newPrice: "400",
    price: "₹280",
    category: "m-display",
    color: "tgtkey",
    link:`/card121dlx`,
  },
  {
    id: 6,
    img: "./image/141E1.jpg",
    title: "MI-141E",
    star:"Desk Calculator",
    prevPrice: "₹580",
    newPrice: "501",
    price: "₹406",
    category: "l-display",
    color: "tgtkey",
    link:`/card141e`,
  },  
  {
    id: 7,
    img: "./image/512GC1 WHITE.jpg",
    title: "MI-512GC",
    star:"Desktop Calculator",
    prevPrice: "₹410",
    newPrice: "400",
    price: "₹287",
    category: "m-display",
    color: "gtkey",
    link:`/card512gc`,
  },
  {
    id: 8,
    img: "./image/556N2.jpg",
    title: "MI-556N",
    star:"Desktop Calculator",
    prevPrice: "₹420",
    newPrice: "400",
    price: "₹294",
    category: "m-display",
    color: "tax",
    link:`/card556n`,
  },
  {
    id: 9,
    img: "./image/GT1.jpg",
    title: "MI-512GT",
    star:"Desktop Calculator",
    prevPrice: "₹390",
    newPrice: "400",
    price: "₹273",
    category: "m-display",
    color: "tax",
    link:`/card512gt`,
  },
  {
    id: 10,
    img: "./image/837N1.jpg",
    title: "MI-837N",
    star:"Desktop Calculator",
    prevPrice: "₹385",
    newPrice: "400",
    price: "₹270",
    category: "m-display",
    color: "gtkey",
    link:`/card837n`,
  },
  {
    id: 11,
    img: "./image/888N1.jpg",
    title: "MI-888N",
    star:"Desktop Calculator",
    prevPrice: "₹460",
    newPrice: "500",
    price: "₹322",
    category: "m-display",
    color: "gtkey",
    link:`/card888n`,
  },
  {
    id: 12,
    img: "./image/913VS2 copy.jpg",
    title: "913 VS",
    star:"Compact Calculator",
    prevPrice: "₹265",
    newPrice: "400",
    price: "₹186",
    category: "m-display",
    color: "black",
    link:`/card913vs`,
  },
  {
    id: 13,
    img: "./image/847-1.jpg",
    title: "MI-847",
    star:"Desktop Calculator",
    prevPrice: "₹400",
    newPrice: "400",
    price: "₹280",
    category: "m-display",
    color: "gtkey",
    link:`/card847`,
  },
  {
    id: 14,
    img: "./image/786N1.png.jpg",
    title: "MI-786N",
    star:"Desktop Calculator",
    prevPrice: "₹330",
    newPrice: "400",
    price: "₹231",
    category: "m-display",
    color: "gtkey",
    link:`/card786n`,
  },
  {
    id: 15,
    img: "./image/120d1.jpg",
    title: "MJ-120D",
    star:"Desktop Calculator",
    prevPrice: "₹430",
    newPrice: "400",
    price: "₹301",
    category: "m-display",
    color: "tgtkey",
    link:`/card120d`,
  },
  {
    id: 16,
    img: "./image/513WT1.jpg",
    title: "WT-513",
    star:"Desktop Calculator",
    prevPrice: "₹275",
    newPrice: "400",
    price: "₹192",
    category: "m-display",
    color: "gtkey",
    link:`/card513`,
  },
  {
    id: 17,
    img: "./image/912VS1.jpg",
    title: "MI-912",
    star:"Compact Calculator",
    prevPrice: "₹230",
    newPrice: "400",
    price: "₹161",
    category: "m-display",
    color: "black",
    link:`/card912`,
  },
  // {
  //   id: 18,
  //   img: "./image/222N1.jpg",
  //   title: "MI-222N",
  //   star:"Gold Large Calculator",
  //   prevPrice: "₹399",
  //   newPrice: "200",
  //   price: "₹199",
  //   category: "m-display",
  //   color: "black",
  // link:`/probir`,
  // },
 
  // {
  //   id: 20,
  //   img: "./image/200N1.jpg",
  //   title: "MI-200N",
  //   star:"Gold Large Calculator",
  //   prevPrice: "₹219",
  //   newPrice: "200",
  //   price: "₹109",
  //   category: "s-display",
  //   color: "black",
  // },
  {
    id: 21,
    img: "./image/201N1.jpg",
    title: "MI-201N",
    star:"Pocket Calculator",
    prevPrice: "₹125",
    newPrice: "200",
    price: "₹88",
    category: "s-display",
    color: "black",
    link:`/card201`,
  },
];

export default data;
